name: CI

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cargo install wasm-bindgen-cli -f

    - name: Install target
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Build project
      run: |
        cargo build --verbose --target "wasm32-unknown-unknown"
        wasm-bindgen --target web --no-typescript --out-dir src/wasm target/wasm32-unknown-unknown/release/asteroids.wasm

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: src
